"""empty message

Revision ID: 1fe37ac6dbcf
Revises: a157b5065922
Create Date: 2019-12-14 09:18:32.056751

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1fe37ac6dbcf'
down_revision = 'a157b5065922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user',
                  sa.Column('root_certified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'root_certified')
    # ### end Alembic commands ###
