"""empty message

Revision ID: 55b281eb024d
Revises: 
Create Date: 2019-12-17 23:11:11.169509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b281eb024d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sparkle', sa.Column('like_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sparkle', 'like_count')
    # ### end Alembic commands ###
