"""empty message

Revision ID: 6c8fcb2b87f2
Revises: 
Create Date: 2019-12-13 01:09:50.821903

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6c8fcb2b87f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contain')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contain',
                    sa.Column('container_id', sa.INTEGER(), nullable=False),
                    sa.Column('contained_id', sa.INTEGER(), nullable=False),
                    sa.Column('timestamp', sa.DATETIME(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['contained_id'],
                        ['post.id'],
                    ),
                    sa.ForeignKeyConstraint(
                        ['container_id'],
                        ['domain.id'],
                    ), sa.PrimaryKeyConstraint('container_id', 'contained_id'))
    # ### end Alembic commands ###
