"""empty message

Revision ID: 73798244fb80
Revises: ca48c78ddc46
Create Date: 2020-01-12 14:34:45.610615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73798244fb80'
down_revision = 'ca48c78ddc46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('sparkle', 'like_count')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('sparkle', sa.Column('like_count', sa.INTEGER(), nullable=True))
    pass
    # ### end Alembic commands ###
