"""empty message

Revision ID: 84e6fc559283
Revises: e0551052bd72
Create Date: 2020-01-15 15:08:55.941268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e6fc559283'
down_revision = 'e0551052bd72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('voter_count', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'deleted')
    op.drop_column('comment', 'voter_count')
    # ### end Alembic commands ###
