"""empty message

Revision ID: 9a73ea0f773a
Revises: c08d1dd79177
Create Date: 2020-01-13 13:46:47.819021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a73ea0f773a'
down_revision = 'c08d1dd79177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('category_group',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('title', sa.String(length=30), nullable=True),
    #sa.PrimaryKeyConstraint('id'),
    #sa.UniqueConstraint('title')
    #)
    #op.add_column('category', sa.Column('category_group_id', sa.Integer(), nullable=True))
    #op.create_foreign_key(None, 'category', 'category_group', ['category_group_id'], ['id'])
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'category', type_='foreignkey')
    #op.drop_column('category', 'category_group_id')
    #op.drop_table('category_group')
    # ### end Alembic commands ###
    pass
