"""empty message

Revision ID: a157b5065922
Revises: d826027b495c
Create Date: 2019-12-14 00:44:05.573555

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a157b5065922'
down_revision = 'd826027b495c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'classify', sa.Column('classified_id', sa.Integer(), nullable=False),
        sa.Column('classifier_id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['classified_id'],
            ['post.id'],
        ), sa.ForeignKeyConstraint(
            ['classifier_id'],
            ['category.id'],
        ), sa.PrimaryKeyConstraint('classified_id', 'classifier_id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classify')
    # ### end Alembic commands ###
