"""empty message

Revision ID: d826027b495c
Revises: 6c8fcb2b87f2
Create Date: 2019-12-13 01:49:00.405595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd826027b495c'
down_revision = '6c8fcb2b87f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregate',
    sa.Column('aggregator_id', sa.Integer(), nullable=False),
    sa.Column('aggregated_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aggregated_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['aggregator_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('aggregator_id', 'aggregated_id')
    )
    op.create_table('depend',
    sa.Column('depended_id', sa.Integer(), nullable=False),
    sa.Column('dependant_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dependant_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['depended_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('depended_id', 'dependant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('depend')
    op.drop_table('aggregate')
    # ### end Alembic commands ###
